#!/usr/bin/env python3
"""Regenerate app/core/ffmpeg_pins.py from official upstream FFmpeg releases.

Sources (S5: official releases over HTTPS, pinned SHA-256):
- Windows / Linux: BtbN/FFmpeg-Builds: the most recent *dated* autobuild tag
  (immutable, unlike the rolling "latest" tag). Asset SHA-256 comes from the
  GitHub API's digest field.
- macOS: evermeet.cx: versioned (immutable) URLs. The API publishes GPG sigs
  but no SHA-256, so this script downloads each archive and hashes it here;
  end-user machines then verify every fetch against the recorded pin.

Run: python scripts/update_ffmpeg_pins.py
"""

from __future__ import annotations

import hashlib
import sys
from datetime import UTC, datetime
from pathlib import Path

import httpx

REPO_ROOT = Path(__file__).resolve().parents[1]
PINS_FILE = REPO_ROOT / "app" / "core" / "ffmpeg_pins.py"

BTBN_RELEASES = "https://api.github.com/repos/BtbN/FFmpeg-Builds/releases?per_page=10"
EVERMEET_INFO = "https://evermeet.cx/ffmpeg/info/{tool}/release"

# platform key -> substring that identifies the BtbN asset
BTBN_ASSETS = {
    "linux-x86_64": "linux64-gpl.tar.xz",
    "linux-aarch64": "linuxarm64-gpl.tar.xz",
    "windows-x86_64": "win64-gpl.zip",
}

HEADER = '''"""Pinned FFmpeg builds (S5). GENERATED by scripts/update_ffmpeg_pins.py: do not edit.

Every URL is immutable (dated release tag / versioned file) and every archive
is verified against its SHA-256 before a single byte of it is executed.

Generated: {generated}
BtbN release tag: {tag}
evermeet version: {evermeet_version}
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class PinnedArchive:
    url: str
    sha256: str
    format: str  # "tar.xz" | "zip"


#: platform key (see app.core.ffmpeg.platform_key) -> archives to install.
PINS: dict[str, tuple[PinnedArchive, ...]] = {{
'''


def btbn_pins(client: httpx.Client) -> tuple[str, dict[str, tuple[str, str]]]:
    releases = client.get(BTBN_RELEASES).raise_for_status().json()
    release = next(r for r in releases if r["tag_name"].startswith("autobuild-"))
    tag = release["tag_name"]
    pins: dict[str, tuple[str, str]] = {}
    for platform, marker in BTBN_ASSETS.items():
        asset = next(
            a for a in release["assets"] if a["name"].endswith(marker) and "shared" not in a["name"]
        )
        digest = asset["digest"]
        if not digest or not digest.startswith("sha256:"):
            raise RuntimeError(f"no sha256 digest for {asset['name']}")
        pins[platform] = (asset["browser_download_url"], digest.removeprefix("sha256:"))
    return tag, pins


def evermeet_pins(client: httpx.Client) -> tuple[str, list[tuple[str, str]]]:
    archives: list[tuple[str, str]] = []
    version = ""
    for tool in ("ffmpeg", "ffprobe"):
        info = client.get(EVERMEET_INFO.format(tool=tool)).raise_for_status().json()
        version = info["version"]
        url = info["download"]["zip"]["url"]
        print(f"hashing {url} ...", flush=True)
        digest = hashlib.sha256()
        with client.stream("GET", url) as response:
            response.raise_for_status()
            for chunk in response.iter_bytes(1 << 20):
                digest.update(chunk)
        archives.append((url, digest.hexdigest()))
    return version, archives


def main() -> int:
    with httpx.Client(follow_redirects=True, timeout=120) as client:
        tag, btbn = btbn_pins(client)
        evermeet_version, darwin = evermeet_pins(client)

    lines = [
        HEADER.format(
            generated=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
            tag=tag,
            evermeet_version=evermeet_version,
        )
    ]
    for platform, (url, sha) in btbn.items():
        fmt = "zip" if url.endswith(".zip") else "tar.xz"
        lines.append(
            f'    "{platform}": (\n'
            f"        PinnedArchive(\n"
            f'            url="{url}",\n'
            f'            sha256="{sha}",\n'
            f'            format="{fmt}",\n'
            f"        ),\n"
            f"    ),\n"
        )
    for platform in ("darwin-x86_64", "darwin-arm64"):  # evermeet is x86_64 (Rosetta on arm)
        entries = "".join(
            f"        PinnedArchive(\n"
            f'            url="{url}",\n'
            f'            sha256="{sha}",\n'
            f'            format="zip",\n'
            f"        ),\n"
            for url, sha in darwin
        )
        lines.append(f'    "{platform}": (\n{entries}    ),\n')
    lines.append("}\n")
    PINS_FILE.write_text("".join(lines))
    print(f"wrote {PINS_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
