"""Pinned FFmpeg builds (S5). GENERATED by scripts/update_ffmpeg_pins.py - do not edit.

Every URL is immutable (dated release tag / versioned file) and every archive
is verified against its SHA-256 before a single byte of it is executed.

Generated: 2026-07-07 12:05 UTC
BtbN release tag: autobuild-2026-07-06-14-19
evermeet version: 8.1.2
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class PinnedArchive:
    url: str
    sha256: str
    format: str  # "tar.xz" | "zip"


#: platform key (see app.core.ffmpeg.platform_key) -> archives to install.
PINS: dict[str, tuple[PinnedArchive, ...]] = {
    "linux-x86_64": (
        PinnedArchive(
            url="https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-07-06-14-19/ffmpeg-N-125478-gc6498178bb-linux64-gpl.tar.xz",
            sha256="33a36533fecee4b8d04f46444952d57a0123fcdd90811e80fb276033a5604211",
            format="tar.xz",
        ),
    ),
    "linux-aarch64": (
        PinnedArchive(
            url="https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-07-06-14-19/ffmpeg-N-125478-gc6498178bb-linuxarm64-gpl.tar.xz",
            sha256="83a66e51c92d16a1035426b7a2f5bd2bdd9c9aa3d444656a415dd71c52903888",
            format="tar.xz",
        ),
    ),
    "windows-x86_64": (
        PinnedArchive(
            url="https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2026-07-06-14-19/ffmpeg-N-125478-gc6498178bb-win64-gpl.zip",
            sha256="7043c01cf831ea96d983baaa729b4a6c24fde657a66005ed1f9f21bae564f491",
            format="zip",
        ),
    ),
    "darwin-x86_64": (
        PinnedArchive(
            url="https://evermeet.cx/ffmpeg/ffmpeg-8.1.2.zip",
            sha256="e91df72a1ee7c26606f90dd2dd4dcccc6a75140ff9ea6fdd50faae828b82ba69",
            format="zip",
        ),
        PinnedArchive(
            url="https://evermeet.cx/ffmpeg/ffprobe-8.1.2.zip",
            sha256="399b93f0b9862f69767afa343e90c2f48d7e7958cadbb6deb76a012d0e3b7ce3",
            format="zip",
        ),
    ),
    "darwin-arm64": (
        PinnedArchive(
            url="https://evermeet.cx/ffmpeg/ffmpeg-8.1.2.zip",
            sha256="e91df72a1ee7c26606f90dd2dd4dcccc6a75140ff9ea6fdd50faae828b82ba69",
            format="zip",
        ),
        PinnedArchive(
            url="https://evermeet.cx/ffmpeg/ffprobe-8.1.2.zip",
            sha256="399b93f0b9862f69767afa343e90c2f48d7e7958cadbb6deb76a012d0e3b7ce3",
            format="zip",
        ),
    ),
}
